name: {{cookiecutter.projectName}}
options:
  xcodeVersion: 10.4
  minimumXcodeGenVersion: 2.6.0
settings:
  base:
    DEVELOPMENT_TEAM: {{cookiecutter.teamId}}
    SWIFT_VERSION: "5.0"  
targets:
  iOS Application:
    type: application
    platform: iOS
    deploymentTarget: {{cookiecutter.deploymentTarget}}
    scheme: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: {{cookiecutter.bundleIdentifier}}
    info:
      path: iOS Application/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: {{cookiecutter.projectName}}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: YES
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UIRequiredDeviceCapabilities: [armv7]
        ITSAppUsesNonExemptEncryption: NO
        LSRequiresIPhoneOS: YES
        _Configuration: $(CONFIGURATION)  
    sources:
      - iOS Application/
    preBuildScripts:
      - script: |
                "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/iOS Application/Sources/R.generated.swift"
        name: R.Swift generate
        inputFiles: 
          - $(TEMP_DIR)/rswift-lastrun
        outputFiles:
          - $(SRCROOT)/iOS Application/Sources/R.generated.swift
    postCompileScripts:
      - script: |
                ${PODS_ROOT}/SwiftLint/swiftlint
        name: SwiftLint  
  iOS Application Tests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - iOS Application Tests/
    dependencies:
      - target: iOS Application
    scheme:
      testTargets:
        - iOS Application Tests
      gatherCoverageData: true   
  iOS Application UI Tests:
    platform: iOS
    type: bundle.ui-testing
    sources:
      - iOS Application UI Tests/
    dependencies:
      - target: iOS Application
    scheme:
      testTargets:
        - iOS Application UI Tests
      gatherCoverageData: true          